name: java workflow
on:
  push:
    branches:
      "main"
jobs:
  main_workflow:
    name : main_workflow
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: mvn clean 
        run : mvn clean package
        shell: bash 
