name: java workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  main_workflow:
    name: trigger-main-branch
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "push happened to main branch"