name: java workflow
on:
  workflow_dispatch:
  push:
    branches: 
     - "main"

jobs:
  triggerd_workflow:
    name : trigger-main-branch
    runs-on: ubuntu-latest
    
    steps:
      run: echo "push happen to main branch"
      
